# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=3)),
                ('To', models.CharField(max_length=3)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Rate', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
            },
        ),
    ]
