# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreigncurrencyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='Rate',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
