# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreigncurrencyapp', '0002_auto_20180722_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='Rate',
            field=models.IntegerField(),
        ),
    ]
