# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreigncurrencyapp', '0003_dailyrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrate',
            old_name='exchange_id',
            new_name='exchange',
        ),
    ]
