# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreigncurrencyapp', '0004_auto_20180722_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='from_currency_id',
            new_name='from_currency',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='to_currency_id',
            new_name='to_currency',
        ),
    ]
